module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.MESSAGE_ROOM_SEND = "SOCKET_CONNECTED";
/* module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
 */

