export const SOCKET_CONNECTED = "SOCKET_CONNECTED";

export const SOCKET_USER_LOGIN = "SOCKET_USER_LOGIN";
export const SOCKET_LOGIN_SUCCESS = "SOCKET_LOGIN_SUCCESS";
export const SOCKET_LOGIN_FAILTURE = "SOCKET_LOGIN_FAILTURE";
